# Generated by Django 3.1 on 2020-08-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NesaraTours', '0002_auto_20200831_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='Status',
            field=models.CharField(choices=[('Compleated', 'Compleated'), ('Not Compleated', 'Not Compleated')], max_length=255, null=True),
        ),
    ]
