# Generated by Django 3.1 on 2020-09-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NesaraTours', '0003_tour_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='Status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Not complete', 'Not complete'), ('Ongoing', 'Ongoing')], max_length=255, null=True),
        ),
    ]
