# Generated by Django 3.1 on 2020-09-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NesaraTours', '0004_auto_20200901_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='Price',
        ),
    ]
