# Generated by Django 3.1.1 on 2020-10-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NesaraTours', '0005_remove_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='Price',
            field=models.IntegerField(null=True),
        ),
    ]
